### ISSUE TITLE
[divider]: add component for dividers

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#407]
For using inside Action Group component and maybe other issues.
can be based on [fast-divider](https://explore.fast.design/components/fast-divider).

- **Orientation**: Should the separator be both horizontal & vertical?
- **size**: should it have a basic size? 
-- Horizontal - can get width 100%;
-- Vertical - 100% of what?
- **Space**: should we add margin? (in action-group it was needed)

**Comment by jshenkman** [comment]
The design for Separator is [here](https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=14736%3A65896).

Orientation: both horizontal & vertical
Size: Currently, we have one size. Maybe we will want one or two more sizes according to the thickness of the line.
-- Horizontal - can get width 100%;
-- Vertical - 100% height of the component. For example, in the action-group we needed a vertical separator 100% height of the container minus the margins. 
Space: I think the component will need to take care of the margins/spacing because each component will have different properties.
