### ISSUE TITLE
Control vwc-text-field font size

### ISSUE THREAD

**Issue by TamirVonage** [Vonage/vivid-3#546]
### The problem

On iOS - when using the `vwc-text-field` component the browser zoom-in on the `vwc-text-field` and distort the whole page layout

### The solution

enabling font size control on the `vwc-text-field` component

### Application/website

web chat

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by rachelbt** [comment]
@TamirVonage not sure we need to expose the font size control, but need to change it to al least 16px in mobile to solve this problem.

**Comment by TamirVonage** [comment]
@rachelbt No objection there. We just need any solution.

**Comment by yinonov** [comment]
This behaviour affect all vonage and is inherited from the Volta parity AFAIK. Making a change to the base & body font size will need to be addressed by design.

Note: this is not a blocker for the frontier web chat nor is text field issue alone. It is a typical browser behaviour for when font size is less than 16 within inputs (in certain viewports).

@TamirVonage would u please mention designers involved here? And whom specifically from design this request comes from? We'll need a bit of research

**Comment by TamirVonage** [comment]
Yamit is involved in this project but I doubt she has a github account

**Comment by yinonov** [comment]
access to this repo and content is publicly available. it's ok to discuss further on JIRA if need be
@Vonage/vivid-design can u please mention this task to Yamit and assign?

**Comment by yinonov** [comment]
will be resolved by redefining tokens for different platforms
