### ISSUE TITLE
[dialog]: add horizontal position for icon

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#848]
details are here: https://jira.vonage.com/browse/VIV-825

**things to consider:**
1. Currently we have headline and text - we **do not have subtitle** as shown in the design in Jira:
![image](https://user-images.githubusercontent.com/7512792/202907078-81c1b1d2-deb4-49a0-995a-30e532d83ad8.png)
**we do have** `text `member which is for the content text. If the developer should add content with `slot="content"` the text will not show up.
2. the icon is in the graphics slot. Not sure it will cause problem but need to be remembered.
3. In case the headline is more than one line - is the icon need to be centered like this:
![image](https://user-images.githubusercontent.com/7512792/202907330-47cb97f5-b644-4c88-ba1a-8aa343146492.png)
4. In the design there are borders to the content - are we adding this to the design? Is it optional? what if there's only headline and footer buttons? This need to have further behaviour options

**Comment by rachelbt** [comment]
@AyalaBu mind having a look - maybe I am missing something in the Jira issue?

**Comment by yinonov** [comment]
1. you're right. dialog does not feature a subtitle in all versions of vivid, but it doesn't block progress of this request.
2. to apply same size to icon or any other assigned graphic, use internal css variable to assign size value to. that way, icon could refer to it and also authors overriding icon with graphic could refer to it if they need to. it's convenient.
3. in note, the icon aligns to top. keep the convention
4. no. it's out of scope of the JIRA ticket

**Comment by AyalaBu** [comment]
@yinonov @rachelbt 
This is the link to the newest version of the component:
https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=16074%3A74746&t=Un7T3AAxsb6p7yRh-1

The borders mentioned in the ticket function as content dividers in the new component,
and even if don't exist right now should be considered,
since they organize the content and create hierarchy.

Also, after conversation with Racheli:
despite we currently don't have a subtitle in the component, it is still needed and should be developed.

**Comment by yinonov** [comment]
@AyalaBu these are unrelated to the scope of the JIRA ticket, which is targeted to enable different icon positioning.
Let's address, discuss and develop other features against other tickets
